# version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./certs:/certs:ro
    environment:
      - PYTHONUNBUFFERED=1
  nginx:
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - backend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
