apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-app
  template:
    metadata:
      labels:
        app: secure-app
    spec:
      containers:
      - name: secure-container
        image: nginx:latest  # or your custom image
        ports:
        - containerPort: 443
        volumeMounts:
        - name: tls-certs
          mountPath: "/etc/certs"
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: server-tls
