apiVersion: v1
kind: Pod
metadata:
  name: encrypted-pod
spec:
  containers:
  - name: app-container
    image: alpine
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: encrypted-volume
      mountPath: /data
  volumes:
  - name: encrypted-volume
    persistentVolumeClaim:
      claimName: encrypted-pvc
